name: Build Linux Container Image and Push to ACR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: app
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: my0acr.azurecr.io
        username: my0acr
        password: WDi1f6JwWw0pP+I/kPN0pYpIwjkNfkFVU/LrFWE0za+ACRDyZ2ig
    - run: |
        docker build . -t my0acr.azurecr.io/repository-name:${{ github.sha }}
        docker push my0acr.azurecr.io/repository-name:${{ github.sha }}
