name: Run Azure Login with OIDC
on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: cb32306e-9f2e-442f-92a6-9d18ff546249
  
      - name: 'Run az commands'
        run: |
          az account show
          az group list
