name: Run Azure Login with OIDC
on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: TEST
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0985BF9FBCCB4C8B8BF08EA1057720BE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_86dc76a2-6ebe-49a0-889d-e26772bced66 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_cb32306e-9f2e-442f-92a6-9d18ff546249 }}
  
      - name: 'Run az commands'
        run: |
          az account show
          az group list
