name: Build and deploy Python app to Azure Web App - ML--API

on:
  push:
    branches:
      - default
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockers/Dockerfile
          push: true
          tags: ziadsakr/testapi:test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Login to Azure
        uses: az login

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-container-deploy@v1
        with:
          app-name: 'ML--API'
          images: ${{ secrets.ACR_LOGIN_SERVER }}/ml-api:latest
