name: Build and deploy Python app to Azure Web App - ML--API

on:
  push:
    branches:
      - default
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: Dockerfile
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/ml-api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9FBDE08064C442C8AE71A4E1B953C2DC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A24694A3673A4476A0399BD42C3F7F15 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5D96A25E72C84DF3AD920DE066A978D7 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-container-deploy@v2
        with:
          app-name: 'ML--API'
          images: ${{ secrets.ACR_LOGIN_SERVER }}/ml-api:latest
